Algoritmo "semnome"
// Disciplina: [Linguagem e Lógica de Programação]
// Professor: João Luís Figueiró
// Descrição: Primeiro exemplo com números aleatórios
// Autor(a): Kauã Queiroga
// Data atual: 21/06/2023
Var
// Seção de Declarações das variáveis 
num_aleatorio:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

num_aleatorio <- randi(10)

escreval("Número aleatório gerado: ",num_aleatorio)

Fimalgoritmo