Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : João Luis Figueró
// Descrição   : Mensagem de boas-vindas
// Autor(a)    : Kauã Queiroga
// Data atual  : 12/06/2023
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Olá mundo!")
escreval("Programar é bom!")
escreva("Quero jogar KOF.")

Fimalgoritmo