Algoritmo "exemplo4-laços-de-repetição"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : João Luís Figueiró
// Descrição   : Exemplo 4 de laços de repetição
// Autor(a)    : Kauã Queiroga
// Data atual  : 20/06/2023
Var
// Seção de Declarações das variáveis 
contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para contador de 100 ate 1000 faca

    escreval(contador*10)
    
    fimpara

Fimalgoritmo